version: '3'
services:
  app:
    image: node:latest
    # other configs
  whoiam:
    image: alpine:3.15.0
    # other configs
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30
    restart: always