version: '3'
networks:
  sk_network:
services:
  app:
    image: sinke-registry:5000/sk-nginx:stable-alpine3.18
    container_name: app
    ports:
      - 9000:8000  # Map host port 9000 to container port 8000
    # Add other necessary configurations for the app service
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    env_file:
      - .env

#  whoiam:
#    image: localhost:5000/sk-redis:7.2.4
#    container_name: whoiam
#    ports:
#      - 8081:8080  # Map host port 8081 to container port 8080
#    # Add other necessary configurations for the whoiam service
#    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
#    env_file:
#      - .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/docker/config.json:/root/.docker/config.json:ro
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: enowsinke@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: enowsinke@gmail.com,mathiassinke@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
    command: --interval 30 --debug
    restart: always
    networks:
      sk_network:
    links:
      - reg:sinke-registry

  reg:
    image: registry:2
    container_name: sinke-registry
    restart: always
    ports:
      - "5000:5000"
    networks:
      sk_network:
    volumes:
      - registry_data:/var/lib/registry
volumes:
  registry_data: {}
